### ISSUE TITLE
apparently broken OpenACC directive 

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CICE#24]
NVFORTRAN-S-0034-Syntax error at or near ACCLOOP (/glade/work/jedwards/sandboxes/cesm2_x_alpha/components/cice/src/cicecore/cicedynB/dynamics/ice_dyn_evp_1d.F90: 906)
  0 inform,   0 warnings,   1 severes, 0 fatal for evp1d_halo_update

using: Currently Loaded Modules:
  1) ncarenv/1.3    3) nvhpc/22.2      5) netcdf-mpi/4.8.1   7) esmf-8.4.0b08_casper-ncdfio-openmpi-O   9) pio/2.5.9
  2) cmake/3.18.2   4) openmpi/4.1.4   6) pnetcdf/1.12.3     8) ncarcompilers/0.5.0

**Comment by dabail10** [comment]
Thanks for finding this. I have some updates to this module coming soon. This does not impact standard simulations.

**Comment by jedwards4b** [comment]
Broken OpenACC directives in cice may cause errors in cases which are using OpenACC in other components.  I hope that we can soon include one or more OpenACC builds in our test suite.

**Comment by dabail10** [comment]
Looks like this is still there in the Consortium. Can you tell me what the syntax error is exactly and I will add it to an issue for the Consortium.

**Comment by jedwards4b** [comment]
I'm afraid that this is all the information provided by the compiler and I am no GPU expert.  I also tried nvhpc/22.5 and got the same error.

**Comment by dabail10** [comment]
Ok. I'll do some google searching on it.

**Comment by dabail10** [comment]
Can you test out the following?

!$acc present(uvel, vvel)
Thus "&" is removed

**Comment by jedwards4b** [comment]
Sorry for the long delay in responding.  That change does indeed solve the problem, but it is still present in main on ESCOMP - can we keep the issue open until the problem is solved in a tagged cice version?

**Comment by dabail10** [comment]
Sure. The alpha12f tag will have the latest CICE that includes this fix.

**Comment by jedwards4b** [comment]
I meant cice tag, not cesm tag, but okay - thank you.  This change is not in cice main yet - are you going to slam us with a lot of cice changes all at once?

**Comment by dabail10** [comment]
This fix is in ESCOMP/CICE main. Not sure what you are looking at. This fix was in cice6_4_0_1 from December. In fact, this tag was brought in to cesm2_3_alpha12b. I do have some additional changes that are fixes in CICE.

**Comment by jedwards4b** [comment]
stupid error, i'm sorry.
