### ISSUE TITLE
Excessive output from cice6

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CICE#26]
Do we need this output from every ice task?  How about if we just do task 0 unless debug is on then we do all tasks?

dec2340.hsn.de.hpc.ucar.edu 739:  (ice_comp_nuopc):(InitializeAdvertise)WARNING: tfrz_option from driver linear_s
dec2340.hsn.de.hpc.ucar.edu 739:  alt is overwriting tfrz_option from cice namelist mushy
dec2340.hsn.de.hpc.ucar.edu 739:  (ice_comp_nuopc):(InitializeAdvertise)WARNING: atmiter_ from driver   0.10000D-
dec2340.hsn.de.hpc.ucar.edu 739:  01 is overwritting atmiter_conv from cice namelist   0.00000D+00

**Comment by dabail10** [comment]
I will add this to the cap.

**Comment by dabail10** [comment]
This is fixed in cesm_cice6_4_1_12. I need to add it to a CESM tag.
