### ISSUE TITLE
option REST_OPTION=end not supported

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CICE#29]
This is a documented option to set the restart alarm but I found that it was not
supported in cice.

**Comment by dabail10** [comment]
Did we decide to close this?

**Comment by jedwards4b** [comment]
No - the issue is still there, I am planning to address it in an upcoming tag.

**Comment by DeniseWorthen** [comment]
We've added a small change to the cap to allow it to use the ``write_restart_at_endofrun`` configuration option in both CICE6 and MOM6. CMEPS had this option, but neither CICE or MOM6 made use of it. Is that the same functionality as "rest_option=end"?
